SET FOREIGN_KEY_CHECKS=0;
INSERT IGNORE INTO `trader_items` VALUES(295, '100Rnd_762x51_M240', 1, 'Ammo - Light Machine Gun', 'trade_items'),
(296, '100Rnd_762x54_PK', 1, 'Ammo - Light Machine Gun ', 'trade_items'),
(297, '5Rnd_86x70_L115A1', 1, 'Ammo Rifle Sniper', 'trade_items'),
(298, '10Rnd_762x54_SVD', 1, 'Ammo Rifle Sniper', 'trade_items'),
(299, '10x_303', 1, 'Ammo - Rifle', 'trade_items'),
(300, '15Rnd_9x19_M9', 1, 'Ammo Pistol', 'trade_items'),
(301, '15Rnd_9x19_M9SD', 1, 'Ammo Pistol', 'trade_items'),
(302, '15Rnd_W1866_Slug', 1, 'Ammo Shotgun', 'trade_items'),
(303, '17Rnd_9x19_glock17', 1, 'Ammo Pistol', 'trade_items'),
(304, '1Rnd_HE_M203', 1, 'Ammo - Grenade', 'trade_items'),
(305, '1Rnd_Smoke_M203', 1, 'Ammo - Smoke', 'trade_items'),
(306, '200Rnd_556x45_M249', 1, 'Ammo - Light Machine Gun', 'trade_items'),
(307, '20Rnd_762x51_DMR', 1, 'Ammo Rifle Sniper', 'trade_items'),
(308, '20Rnd_762x51_FNFAL', 1, 'Ammo - Rifle', 'trade_items'),
(309, '2Rnd_shotgun_74Pellets', 1, 'Ammo Shotgun', 'trade_items'),
(310, '2Rnd_shotgun_74Slug', 1, 'Ammo Shotgun', 'trade_items'),
(311, '30Rnd_545x39_AK', 1, 'Ammo - Rifle', 'trade_items'),
(312, '30Rnd_556x45_Stanag', 1, 'Ammo - Rifle', 'trade_items'),
(313, '30Rnd_556x45_StanagSD', 1, 'Ammo - Rifle', 'trade_items'),
(314, '30Rnd_762x39_AK47', 1, 'Ammo - Rifle', 'trade_items'),
(315, '30Rnd_762x39_SA58', 1, 'Ammo - Rifle', 'trade_items'),
(316, '30rnd_9x19_MP5', 1, 'Ammo SMG', 'trade_items'),
(317, '30Rnd_9x19_MP5SD', 1, 'Ammo SMG', 'trade_items'),
(318, '30Rnd_9x19_UZI', 1, 'Ammo SMG', 'trade_items'),
(319, '5Rnd_762x51_M24', 1, 'Ammo Rifle Sniper', 'trade_items'),
(320, '5x_22_LR_17_HMR', 1, 'Ammo Rifle Sniper', 'trade_items'),
(321, '64Rnd_9x19_SD_Bizon', 1, 'Ammo SMG', 'trade_items'),
(322, '6Rnd_45ACP', 1, 'Ammo Pistol', 'trade_items'),
(323, '7Rnd_45ACP_1911', 1, 'Ammo Pistol', 'trade_items'),
(324, '8Rnd_9x18_Makarov', 1, 'Ammo Pistol', 'trade_items'),
(325, '8Rnd_B_Beneli_74Slug', 1, 'Ammo Shotgun', 'trade_items'),
(326, '8Rnd_B_Beneli_Pellets', 1, 'Ammo Shotgun', 'trade_items'),
(327, 'AH6X_DZ', 2, 'Helicopter Unarmed', 'trade_any_vehicle'),
(328, 'AKS_74_kobra', 3, 'Rifle', 'trade_weapons'),
(329, 'AKS_74_U', 3, 'Rifle', 'trade_weapons'),
(330, 'AKS_GOLD', 3, 'Rifle', 'trade_weapons'),
(331, 'AK_47_M', 3, 'Rifle', 'trade_weapons'),
(332, 'AK_74', 3, 'Rifle', 'trade_weapons'),
(333, 'AN2_DZ', 2, 'Plane', 'trade_any_vehicle'),
(334, 'ArmoredSUV_PMC_DZ', 2, 'SUV', 'trade_any_vehicle'),
(335, 'ATV_CZ_EP1', 2, 'Offroad', 'trade_any_vehicle'),
(336, 'ATV_US_EP1', 2, 'Offroad', 'trade_any_vehicle'),
(337, 'Binocular', 3, 'ToolBelt', 'trade_weapons'),
(338, 'Binocular_Vector', 3, 'ToolBelt', 'trade_weapons'),
(339, 'bizon_silenced', 3, 'Sub Machine Gun', 'trade_weapons'),
(342, 'WoodenArrow', 1, 'Ammo - Crossbow', 'trade_items'),
(343, 'Quiver', 1, 'Ammo - Crossbow', 'trade_items'),
(344, 'bulk_15Rnd_9x19_M9SD', 1, 'Wholesale Crates', 'trade_items'),
(345, 'bulk_17Rnd_9x19_glock17', 1, 'Wholesale Crates', 'trade_items'),
(346, 'bulk_30Rnd_556x45_StanagSD', 1, 'Wholesale Crates', 'trade_items'),
(347, 'bulk_30Rnd_9x19_MP5SD', 1, 'Wholesale Crates', 'trade_items'),
(351, 'bulk_ItemSandbag', 1, 'Wholesale Crates', 'trade_items'),
(353, 'C130J_US_EP1', 2, 'Plane', 'trade_any_vehicle'),
(354, 'car_hatchback', 2, 'Cars', 'trade_any_vehicle'),
(355, 'car_sedan', 2, 'Cars', 'trade_any_vehicle'),
(356, 'CH_47F_EP1_DZ', 2, 'Helicopter', 'trade_any_vehicle'),
(357, 'Colt1911', 3, 'Pistol', 'trade_weapons'),
(358, 'Crossbow_DZ', 3, 'Weapon', 'trade_weapons'),
(359, 'CSJ_GyroC', 2, 'Helicopter Unarmed', 'trade_any_vehicle'),
(360, 'CSJ_GyroCover', 2, 'Helicopter Unarmed', 'trade_any_vehicle'),
(361, 'CSJ_GyroP', 2, 'Helicopter Unarmed', 'trade_any_vehicle'),
(362, 'CZ_VestPouch_EP1', 2, 'Backpack', 'trade_backpacks'),
(363, 'datsun1_civil_1_open', 2, 'Truck', 'trade_any_vehicle'),
(364, 'datsun1_civil_2_covered', 2, 'Truck', 'trade_any_vehicle'),
(365, 'datsun1_civil_3_open', 2, 'Truck', 'trade_any_vehicle'),
(366, 'DMR', 3, 'Rifle Sniper', 'trade_weapons'),
(367, 'DZ_ALICE_Pack_EP1', 2, 'Backpack', 'trade_backpacks'),
(368, 'DZ_Assault_Pack_EP1', 2, 'Backpack', 'trade_backpacks'),
(369, 'DZ_Backpack_EP1', 2, 'Backpack', 'trade_backpacks'),
(370, 'DZ_British_ACU', 2, 'Backpack', 'trade_backpacks'),
(371, 'DZ_CivilBackpack_EP1', 2, 'Backpack', 'trade_backpacks'),
(372, 'DZ_Czech_Vest_Puch', 2, 'Backpack', 'trade_backpacks'),
(373, 'DZ_Patrol_Pack_EP1', 2, 'Backpack', 'trade_backpacks'),
(374, 'DZ_TK_Assault_Pack_EP1', 2, 'Backpack', 'trade_backpacks'),
(375, 'Fishing_Boat', 2, 'Boats', 'trade_any_boat'),
(376, 'FlareGreen_M203', 1, 'Flares', 'trade_items'),
(377, 'FlareWhite_M203', 1, 'Flares', 'trade_items'),
(378, 'FN_FAL', 3, 'Rifle', 'trade_weapons'),
(379, 'FN_FAL_ANPVS4', 3, 'Rifle', 'trade_weapons'),
(380, 'FoodbaconCooked', 1, 'Food', 'trade_items'),
(381, 'FoodbeefCooked', 1, 'Food', 'trade_items'),
(382, 'FoodCanBakedBeans', 1, 'Food', 'trade_items'),
(383, 'FoodCanFrankBeans', 1, 'Food', 'trade_items'),
(384, 'FoodCanPasta', 1, 'Food', 'trade_items'),
(385, 'FoodCanSardines', 1, 'Food', 'trade_items'),
(386, 'FoodchickenCooked', 1, 'Food', 'trade_items'),
(387, 'FoodmuttonCooked', 1, 'Food', 'trade_items'),
(388, 'FoodrabbitCooked', 1, 'Food', 'trade_items'),
(389, 'G36A_camo', 3, 'Rifle', 'trade_weapons'),
(390, 'G36C', 3, 'Rifle', 'trade_weapons'),
(391, 'G36C_camo', 3, 'Rifle', 'trade_weapons'),
(392, 'G36K_camo', 3, 'Rifle', 'trade_weapons'),
(393, 'G36_C_SD_camo', 3, 'Rifle', 'trade_weapons'),
(395, 'glock17_EP1', 3, 'Pistol', 'trade_weapons'),
(396, 'GLT_M300_LT', 2, 'Cars', 'trade_any_vehicle'),
(397, 'GLT_M300_ST', 2, 'Cars', 'trade_any_vehicle'),
(398, 'HandChemBlue', 1, 'Chemlites', 'trade_items'),
(399, 'HandChemGreen', 1, 'Chemlites', 'trade_items'),
(400, 'HandChemRed', 1, 'Chemlites', 'trade_items'),
(401, 'HandGrenade_west', 1, 'Grenades', 'trade_items'),
(402, 'HandRoadFlare', 1, 'Flares', 'trade_items'),
(403, 'hilux1_civil_1_open', 2, 'Truck', 'trade_any_vehicle'),
(404, 'hilux1_civil_2_covered', 2, 'Truck', 'trade_any_vehicle'),
(405, 'hilux1_civil_3_open_EP1', 2, 'Truck', 'trade_any_vehicle'),
(406, 'HMMWV_Ambulance', 2, 'HMMWVs', 'trade_any_vehicle');
INSERT IGNORE INTO `trader_items` VALUES(407, 'HMMWV_Ambulance_CZ_DES_EP1', 2, 'HMMWVs', 'trade_any_vehicle'),
(408, 'HMMWV_DES_EP1', 2, 'HMMWVs', 'trade_any_vehicle'),
(409, 'HMMWV_DZ', 2, 'HMMWVs', 'trade_any_vehicle'),
(410, 'HMMWV_M1035_DES_EP1', 2, 'HMMWVs', 'trade_any_vehicle'),
(411, 'HMMWV_M1151_M2_CZ_DES_EP1', 2, 'HMMWVs', 'trade_any_vehicle'),
(412, 'HMMWV_M998A2_SOV_DES_EP1', 2, 'HMMWVs', 'trade_any_vehicle'),
(413, 'huntingrifle', 3, 'Rifle Sniper', 'trade_weapons'),
(414, 'Ikarus', 2, 'Buses', 'trade_any_vehicle'),
(415, 'Ikarus_TK_CIV_EP1', 2, 'Buses', 'trade_any_vehicle'),
(416, 'ItemAntibiotic', 1, 'Medical', 'trade_items'),
(417, 'ItemBandage', 1, 'Medical', 'trade_items'),
(418, 'ItemBloodbag', 1, 'Medical', 'trade_items'),
(419, 'ItemCompass', 3, 'ToolBelt', 'trade_weapons'),
(420, 'ItemEpinephrine', 1, 'Medical', 'trade_items'),
(421, 'ItemEtool', 3, 'ToolBelt', 'trade_weapons'),
(422, 'ItemFlashlight', 3, 'ToolBelt', 'trade_weapons'),
(423, 'ItemFlashlightRed', 3, 'ToolBelt', 'trade_weapons'),
(424, 'ItemGenerator', 1, 'Building Supplies', 'trade_items'),
(425, 'ItemGPS', 3, 'ToolBelt', 'trade_weapons'),
(426, 'ItemHatchet', 3, 'ToolBelt', 'trade_weapons'),
(427, 'ItemHeatPack', 1, 'Medical', 'trade_items'),
(428, 'ItemJerrycan', 1, 'Car Parts', 'trade_items'),
(429, 'ItemJerrycanEmpty', 1, 'Car Parts', 'trade_items'),
(430, 'ItemKnife', 3, 'ToolBelt', 'trade_weapons'),
(431, 'ItemMap', 3, 'ToolBelt', 'trade_weapons'),
(432, 'ItemMatchbox', 3, 'ToolBelt', 'trade_weapons'),
(433, 'ItemMorphine', 1, 'Medical', 'trade_items'),
(434, 'ItemPainkiller', 1, 'Medical', 'trade_items'),
(435, 'ItemRadio', 3, 'ToolBelt', 'trade_weapons'),
(436, 'ItemSandbag', 1, 'Building Supplies', 'trade_items'),
(437, 'ItemSodaCoke', 1, 'Drink', 'trade_items'),
(438, 'ItemSodaMdew', 1, 'Drink', 'trade_items'),
(439, 'ItemSodaPepsi', 1, 'Drink', 'trade_items'),
(440, 'ItemSodaRbull', 1, 'Drink', 'trade_items'),
(441, 'ItemTankTrap', 1, 'Building Supplies', 'trade_items'),
(442, 'ItemTentOld', 1, 'Building Supplies', 'trade_items'),
(443, 'ItemToolbox', 3, 'ToolBelt', 'trade_weapons'),
(444, 'ItemVault', 1, 'Building Supplies', 'trade_items'),
(445, 'ItemWatch', 3, 'ToolBelt', 'trade_weapons'),
(446, 'ItemWire', 1, 'Building Supplies', 'trade_items'),
(447, 'Kamaz', 2, 'Trucks Large', 'trade_any_vehicle'),
(449, 'Lada1', 2, 'Cars', 'trade_any_vehicle'),
(450, 'Lada1_TK_CIV_EP1', 2, 'Cars', 'trade_any_vehicle'),
(451, 'Lada2', 2, 'Cars', 'trade_any_vehicle'),
(452, 'Lada2_TK_CIV_EP1', 2, 'Cars', 'trade_any_vehicle'),
(453, 'LadaLM', 2, 'Cars', 'trade_any_vehicle'),
(454, 'LandRover_CZ_EP1', 2, 'Land Rovers', 'trade_any_vehicle'),
(455, 'LandRover_MG_TK_EP1', 2, 'Land Rovers', 'trade_any_vehicle'),
(456, 'LandRover_Special_CZ_EP1', 2, 'Land Rovers', 'trade_any_vehicle'),
(457, 'LandRover_TK_CIV_EP1', 2, 'Land Rovers', 'trade_any_vehicle'),
(458, 'LeeEnfield', 3, 'Rifle', 'trade_weapons'),
(459, 'M1014', 3, 'Shotgun', 'trade_weapons'),
(460, 'M1030_US_DES_EP1', 2, 'Offroad', 'trade_any_vehicle'),
(461, 'BAF_LRR_scoped', 3, 'Rifle Sniper', 'trade_weapons'),
(464, 'M14_EP1', 3, 'Rifle Sniper', 'trade_weapons'),
(465, 'M16A2', 3, 'Rifle', 'trade_weapons'),
(466, 'M16A2GL', 3, 'Rifle', 'trade_weapons'),
(467, 'M16A4_ACG', 3, 'Rifle', 'trade_weapons'),
(468, 'M24', 3, 'Rifle Sniper', 'trade_weapons'),
(469, 'M240_DZ', 3, 'Machine Gun', 'trade_weapons'),
(470, 'M249_DZ', 3, 'Machine Gun', 'trade_weapons'),
(471, 'M40A3', 3, 'Rifle Sniper', 'trade_weapons'),
(472, 'M4A1', 3, 'Rifle', 'trade_weapons'),
(473, 'M4A1_Aim', 3, 'Rifle', 'trade_weapons'),
(474, 'M4A1_AIM_SD_camo', 3, 'Rifle', 'trade_weapons'),
(475, 'M4A1_HWS_GL_camo', 3, 'Rifle', 'trade_weapons'),
(476, 'M4A3_CCO_EP1', 3, 'Rifle', 'trade_weapons'),
(477, 'M9', 3, 'Pistol', 'trade_weapons'),
(478, 'M9SD', 3, 'Pistol', 'trade_weapons'),
(479, 'Makarov', 3, 'Pistol', 'trade_weapons'),
(480, 'MH6J_DZ', 2, 'Helicopter Unarmed', 'trade_any_vehicle'),
(481, 'Mi17_Civilian_DZ', 2, 'Helicopter Unarmed', 'trade_any_vehicle'),
(482, 'Mi17_DZ', 2, 'Helicopter', 'trade_any_vehicle'),
(483, 'PipeBomb', 1, 'Explosives', 'trade_items'),
(484, 'Mk_48_DZ', 3, 'Machine Gun', 'trade_weapons'),
(485, 'MMT_Civ', 2, 'Bikes', 'trade_any_vehicle'),
(486, 'MP5A5', 3, 'Sub Machine Gun', 'trade_weapons'),
(487, 'MP5SD', 3, 'Sub Machine Gun', 'trade_weapons'),
(488, 'MR43', 3, 'Shotgun', 'trade_weapons'),
(490, 'MTVR_DES_EP1', 2, 'Trucks Large', 'trade_any_vehicle'),
(491, 'NVGoggles', 3, 'ToolBelt', 'trade_weapons'),
(492, 'Old_bike_TK_INS_EP1', 2, 'Bikes', 'trade_any_vehicle'),
(493, 'Old_moto_TK_Civ_EP1', 2, 'Offroad', 'trade_any_vehicle'),
(494, 'PartEngine', 1, 'Car Parts', 'trade_items'),
(495, 'PartFueltank', 1, 'Car Parts', 'trade_items'),
(496, 'PartGeneric', 1, 'Car Parts', 'trade_items'),
(497, 'PartGlass', 1, 'Car Parts', 'trade_items'),
(498, 'PartVRotor', 1, 'Car Parts', 'trade_items'),
(499, 'PartWheel', 1, 'Car Parts', 'trade_items'),
(500, 'PartWoodPile', 1, 'Building Supplies', 'trade_items'),
(501, 'PBX', 2, 'Boats', 'trade_any_boat'),
(502, 'Pickup_PK_GUE', 2, 'Trucks Armed', 'trade_any_vehicle'),
(503, 'Pickup_PK_INS', 2, 'Trucks Armed', 'trade_any_vehicle'),
(504, 'Pickup_PK_TK_GUE_EP1', 2, 'Trucks Armed', 'trade_any_vehicle'),
(505, 'policecar', 2, 'Cars', 'trade_any_vehicle'),
(506, 'Remington870_lamp', 3, 'Shotgun', 'trade_weapons'),
(507, 'revolver_EP1', 3, 'Pistol', 'trade_weapons'),
(508, 'revolver_gold_EP1', 3, 'Pistol', 'trade_weapons'),
(509, 'RHIB', 2, 'Boats', 'trade_any_boat'),
(510, 'S1203_ambulance_EP1', 2, 'Vans', 'trade_any_vehicle'),
(511, 'S1203_TK_CIV_EP1', 2, 'Vans', 'trade_any_vehicle'),
(512, 'Sa58P_EP1', 3, 'Rifle', 'trade_weapons'),
(513, 'Sa58V_CCO_EP1', 3, 'Rifle', 'trade_weapons'),
(514, 'Sa58V_EP1', 3, 'Rifle', 'trade_weapons'),
(515, 'Sa58V_RCO_EP1', 3, 'Rifle', 'trade_weapons'),
(516, 'Skin_BanditW1_DZ', 1, 'Clothes Bandit Female', 'trade_items'),
(517, 'Skin_Camo1_DZ', 1, 'Clothes Military', 'trade_items'),
(518, 'Skin_CZ_Special_Forces_GL_DES_EP1_DZ', 1, 'Clothes Hero', 'trade_items'),
(519, 'Skin_Drake_Light_DZ', 1, 'Clothes Hero', 'trade_items'),
(520, 'Skin_Functionary1_EP1_DZ', 1, 'Clothes - Civilian', 'trade_items'),
(521, 'Skin_GUE_Commander_DZ', 1, 'Clothes Rebel', 'trade_items'),
(522, 'Skin_Haris_Press_EP1_DZ', 1, 'Clothes - Civilian', 'trade_items'),
(523, 'Skin_Ins_Soldier_GL_DZ', 1, 'Clothes Rebel', 'trade_items'),
(524, 'Skin_Pilot_EP1_DZ', 1, 'Clothes - Civilian', 'trade_items'),
(525, 'Skin_Priest_DZ', 1, 'Clothes - Civilian', 'trade_items'),
(526, 'Skin_Rocker2_DZ', 1, 'Clothes - Civilian', 'trade_items'),
(527, 'Skin_Rocket_DZ', 1, 'Clothes Military', 'trade_items'),
(528, 'Skin_RU_Policeman_DZ', 1, 'Clothes - Civilian', 'trade_items'),
(529, 'Skin_Sniper1_DZ', 1, 'Clothes Military', 'trade_items'),
(530, 'Skin_Soldier1_DZ', 1, 'Clothes Military', 'trade_items'),
(531, 'Skin_Soldier_Bodyguard_AA12_PMC_DZ', 1, 'Clothes Hero', 'trade_items'),
(532, 'Skin_Soldier_Sniper_PMC_DZ', 1, 'Clothes Military', 'trade_items'),
(533, 'Skin_Soldier_TL_PMC_DZ', 1, 'Clothes Military', 'trade_items'),
(534, 'Skin_Survivor2_DZ', 1, 'Clothes - Civilian', 'trade_items'),
(535, 'Skin_SurvivorW2_DZ', 1, 'Clothes Female', 'trade_items'),
(536, 'Skin_SurvivorW3_DZ', 1, 'Clothes Female', 'trade_items'),
(537, 'Skin_TK_INS_Soldier_EP1_DZ', 1, 'Clothes Rebel', 'trade_items'),
(538, 'Skin_TK_INS_Warlord_EP1_DZ', 1, 'Clothes Rebel', 'trade_items');
INSERT IGNORE INTO `trader_items` VALUES(539, 'Skoda', 2, 'Cars', 'trade_any_vehicle'),
(540, 'SkodaBlue', 2, 'Cars', 'trade_any_vehicle'),
(541, 'SkodaGreen', 2, 'Cars', 'trade_any_vehicle'),
(542, 'SkodaRed', 2, 'Cars', 'trade_any_vehicle'),
(543, 'Smallboat_1', 2, 'Boats', 'trade_any_boat'),
(544, 'Smallboat_2', 2, 'Boats', 'trade_any_boat'),
(545, 'SmokeShell', 1, 'Smoke Grenades', 'trade_items'),
(546, 'SmokeShellGreen', 1, 'Smoke Grenades', 'trade_items'),
(547, 'SmokeShellRed', 1, 'Smoke Grenades', 'trade_items'),
(548, 'SUV_Blue', 2, 'SUV', 'trade_any_vehicle'),
(549, 'SUV_Charcoal', 2, 'SUV', 'trade_any_vehicle'),
(550, 'SUV_Green', 2, 'SUV', 'trade_any_vehicle'),
(551, 'SUV_Orange', 2, 'SUV', 'trade_any_vehicle'),
(552, 'SUV_Pink', 2, 'SUV', 'trade_any_vehicle'),
(553, 'SUV_Red', 2, 'SUV', 'trade_any_vehicle'),
(554, 'SUV_Silver', 2, 'SUV', 'trade_any_vehicle'),
(555, 'SUV_TK_CIV_EP1', 2, 'SUV', 'trade_any_vehicle'),
(556, 'SUV_White', 2, 'SUV', 'trade_any_vehicle'),
(557, 'SUV_Yellow', 2, 'SUV', 'trade_any_vehicle'),
(558, 'SVD_CAMO', 3, 'Rifle Sniper', 'trade_weapons'),
(559, 'tractor', 2, 'Offroad', 'trade_any_vehicle'),
(560, 'TT650_Civ', 2, 'Offroad', 'trade_any_vehicle'),
(561, 'TT650_Ins', 2, 'Offroad', 'trade_any_vehicle'),
(562, 'TT650_TK_CIV_EP1', 2, 'Offroad', 'trade_any_vehicle'),
(563, 'UAZ_CDF', 2, 'Utility', 'trade_any_vehicle'),
(564, 'UAZ_INS', 2, 'Utility', 'trade_any_vehicle'),
(565, 'UAZ_RU', 2, 'Utility', 'trade_any_vehicle'),
(566, 'UAZ_Unarmed_TK_CIV_EP1', 2, 'Utility', 'trade_any_vehicle'),
(567, 'UAZ_Unarmed_TK_EP1', 2, 'Utility', 'trade_any_vehicle'),
(568, 'UAZ_Unarmed_UN_EP1', 2, 'Utility', 'trade_any_vehicle'),
(569, 'UH1H_DZ', 2, 'Helicopter', 'trade_any_vehicle'),
(572, 'Ural_CDF', 2, 'Trucks Large', 'trade_any_vehicle'),
(573, 'Ural_TK_CIV_EP1', 2, 'Trucks Large', 'trade_any_vehicle'),
(574, 'Ural_UN_EP1', 2, 'Trucks Large', 'trade_any_vehicle'),
(575, 'UZI_EP1', 3, 'Sub Machine Gun', 'trade_weapons'),
(576, 'V3S_Open_TK_CIV_EP1', 2, 'Trucks Large', 'trade_any_vehicle'),
(577, 'V3S_Open_TK_EP1', 2, 'Trucks Large', 'trade_any_vehicle'),
(579, 'VolhaLimo_TK_CIV_EP1', 2, 'Cars', 'trade_any_vehicle'),
(580, 'Volha_1_TK_CIV_EP1', 2, 'Cars', 'trade_any_vehicle'),
(581, 'Volha_2_TK_CIV_EP1', 2, 'Cars', 'trade_any_vehicle'),
(582, 'VWGolf', 2, 'Cars', 'trade_any_vehicle'),
(583, 'Winchester1866', 3, 'Shotgun', 'trade_weapons'),
(584, 'Zodiac', 2, 'Boats', 'trade_any_boat'),
(585, 'ItemTrashRazor', 1, 'Medical - Trash', 'trade_items'),
(586, 'ItemTrashToiletpaper', 1, 'Medical - Trash', 'trade_items'),
(588, 'Skin_SurvivorWpink_DZ', 1, 'Clothes Female', 'trade_items'),
(589, 'Skin_SurvivorWcombat_DZ', 1, 'Clothes Female', 'trade_items'),
(590, 'Skin_SurvivorWdesert_DZ', 1, 'Clothes Female', 'trade_items'),
(591, 'Skin_SurvivorWurban_DZ', 1, 'Clothes Female', 'trade_items'),
(592, 'Offroad_DSHKM_Gue', 2, 'Trucks Armed', 'trade_any_vehicle'),
(593, 'Skin_Bandit1_DZ', 1, 'Clothes Bandit', 'trade_items'),
(594, 'Skin_Bandit2_DZ', 1, 'Clothes Bandit', 'trade_items'),
(595, 'Skin_BanditW2_DZ', 1, 'Clothes Bandit Female', 'trade_items'),
(596, 'SCAR_H_LNG_Sniper_SD', 3, 'Rifle Sniper', 'trade_weapons'),
(597, '20Rnd_762x51_SB_SCAR', 1, 'Ammo Rifle Sniper', 'trade_items'),
(598, 'ItemCrowbar', 3, 'Toolbelt', 'trade_weapons'),
(599, 'ItemMachete', 3, 'ToolBelt', 'trade_weapons'),
(600, 'ItemWaterbottleUnfilled', 1, 'Drink', 'trade_items'),
(601, 'Sa61_EP1', 3, 'Sub Machine Gun', 'trade_weapons'),
(602, 'UZI_SD_EP1', 3, 'Sub Machine Gun', 'trade_weapons'),
(603, '30Rnd_9x19_UZI_SD', 1, 'Ammo SMG', 'trade_items'),
(604, '20Rnd_B_765x17_Ball', 1, 'Ammo SMG', 'trade_items'),
(605, 'Pecheneg_DZ', 3, 'Machine Gun', 'trade_weapons'),
(606, 'M79_EP1', 3, 'Grenade Launcher', 'trade_weapons'),
(607, 'MakarovSD', 3, 'Pistol', 'trade_weapons'),
(608, '8Rnd_9x18_MakarovSD', 1, 'Ammo Pistol', 'trade_items'),
(609, '30m_plot_kit', 1, 'Building Supplies', 'trade_items'),
(610, 'UH60M_EP1_DZ', 2, 'Helicopter', 'trade_any_vehicle'),
(611, 'AH64D_EP1', 2, 'Helicopter', 'trade_any_vehicle'),
(612, 'A10_US_EP1', 2, 'Jet Plane', 'trade_any_vehicle'),
(613, 'Su25_TK_EP1', 2, 'Jet Plane', 'trade_any_vehicle'),
(616, 'KamazRefuel_DZ', 2, 'Trucks Refuel New', 'trade_any_vehicle'),
(618, 'MtvrRefuel_DES_EP1_DZ', 2, 'Trucks Refuel New', 'trade_any_vehicle'),
(619, 'UralRefuel_TK_EP1_DZ', 2, 'Trucks Refuel New', 'trade_any_vehicle'),
(620, 'V3S_Refuel_TK_GUE_EP1_DZ', 2, 'Trucks Refuel New', 'trade_any_vehicle'),
(621, 'ItemCorrugated', 1, 'Building Supplies', 'trade_items'),
(622, 'F35B', 2, 'Jet Plane', 'trade_any_vehicle'),
(623, 'UH1Y_DZ', 2, 'Helicopter Armed', 'trade_any_vehicle'),
(624, 'MV22_DZ', 2, 'Helicopter', 'trade_any_vehicle'),
(625, 'Mi24_D_TK_EP1', 2, 'Helicopter Armed', 'trade_any_vehicle'),
(626, 'Skin_FR_OHara_DZ', 1, 'Clothes Military', 'trade_items'),
(627, 'Skin_FR_Rodriguez_DZ', 1, 'Clothes Military', 'trade_items'),
(628, 'Skin_CZ_Soldier_Sniper_EP1_DZ', 1, 'Clothes Military', 'trade_items'),
(629, 'Skin_Graves_Light_DZ', 1, 'Clothes Military', 'trade_items'),
(631, 'SUV_Camo', 2, 'SUV', 'trade_any_vehicle'),
(632, 'DZ_LargeGunBag_EP1', 2, 'Backpack', 'trade_backpacks'),
(633, 'DZ_GunBag_EP1', 2, 'Backpack', 'trade_backpacks'),
(634, 'DZ_CompactPack_EP1', 2, 'Backpack', 'trade_backpacks'),
(635, 'DZ_TerminalPack_EP1', 2, 'Backpack', 'trade_backpacks'),
(636, 'Saiga12K', 3, 'Shotgun', 'trade_weapons'),
(637, '8Rnd_B_Saiga12_74Slug', 1, 'Ammo Shotgun', 'trade_items'),
(638, '8Rnd_B_Saiga12_Pellets', 1, 'Ammo Shotgun', 'trade_items'),
(639, 'SVD_des_EP1', 3, 'Rike Sniper', 'trade_weapons'),
(640, 'SVD', 3, 'Rifle Sniper', 'trade_weapons'),
(641, 'VSS_vintorez', 3, 'Rifle Sniper', 'trade_weapons'),
(642, '10Rnd_9x39_SP5_VSS', 1, 'Ammo Rifle Sniper', 'trade_items'),
(643, '20Rnd_9x39_SP5_VSS', 1, 'Ammo Rifle Sniper', 'trade_items'),
(644, 'm8_compact', 3, 'Rifle', 'trade_weapons'),
(645, 'm8_sharpshooter', 3, 'Rifle', 'trade_weapons'),
(646, 'm8_holo_sd', 3, 'Rifle', 'trade_weapons'),
(647, 'm8_carbine', 3, 'Rifle', 'trade_weapons'),
(648, 'M24_des_EP1', 3, 'Rifle Sniper', 'trade_weapons'),
(649, 'UAZ_MG_TK_EP1', 2, 'Utility Armed', 'trade_any_vehicle'),
(650, 'GAZ_Vodnik', 2, 'Heavy Armor', 'trade_any_vehicle'),
(651, 'GAZ_Vodnik_MedEvac', 2, 'Heavy Armor', 'trade_any_vehicle'),
(652, 'ItemTentDomed', 1, 'Building Supplies', 'trade_items'),
(653, 'ItemTentDomed2', 1, 'Building Supplies', 'trade_items'),
(654, 'ItemPole', 1, 'Building Supplies', 'trade_items'),
(655, 'ItemCanvas', 1, 'Building Supplies', 'trade_items'),
(656, 'PartWoodLumber', 1, 'Building Supplies', 'trade_items'),
(657, 'PartWoodPlywood', 1, 'Building Supplies', 'trade_items'),
(658, 'Skin_Rocker1_DZ', 1, 'Clothes - Civilian', 'trade_items'),
(659, 'Skin_Rocker3_DZ', 1, 'Clothes - Civilian', 'trade_items'),
(660, 'Skin_Rocker4_DZ', 1, 'Clothes - Civilian', 'trade_items'),
(661, 'Skin_GUE_Soldier_2_DZ', 1, 'Clothes Rebel', 'trade_items'),
(662, 'Skin_GUE_Soldier_CO_DZ', 1, 'Clothes Rebel', 'trade_items'),
(663, 'Skin_GUE_Soldier_Crew_DZ', 1, 'Clothes Rebel', 'trade_items'),
(664, 'Skin_GUE_Soldier_Sniper_DZ', 1, 'Clothes Rebel', 'trade_items'),
(665, 'ItemLightBulb', 1, 'Building Supplies', 'trade_items'),
(670, 'ItemBurlap', 1, 'Building Supplies', 'trade_items'),
(671, 'ItemFishingPole', 3, 'Toolbelt', 'trade_weapons'),
(672, 'ItemTroutCooked', 1, 'Food', 'trade_items'),
(673, 'ItemTunaCooked', 1, 'Food', 'trade_items'),
(674, 'ItemSeaBassCooked', 1, 'Food', 'trade_items'),
(675, 'VIL_hilux1_civil', 2, 'Trucks - Vilas', 'trade_any_vehicle'),
(676, 'VIL_hilux1_civi2', 2, 'Trucks - Vilas', 'trade_any_vehicle'),
(677, 'VIL_hilux1_civi3', 2, 'Trucks - Vilas', 'trade_any_vehicle'),
(678, 'VIL_volvofl', 2, 'Truck Cargo - Vilas', 'trade_any_vehicle'),
(679, 'VIL_vwt4_banksec', 2, 'Vans', 'trade_any_vehicle'),
(680, 'VIL_vwt4_civ', 2, 'Vans', 'trade_any_vehicle'),
(681, 'VIL_passat_civil3', 2, 'Cars - Passat - Vilas', 'trade_any_vehicle'),
(682, 'VIL_passat_civil', 2, 'Cars - Passat - Vilas', 'trade_any_vehicle'),
(683, 'VIL_passat_civil4', 2, 'Cars - Passat - Vilas', 'trade_any_vehicle'),
(684, 'VIL_passat_civil5', 2, 'Cars - Passat - Vilas', 'trade_any_vehicle'),
(685, 'VIL_passat_civil1', 2, 'Cars - Passat - Vilas', 'trade_any_vehicle'),
(686, 'VIL_passat_civil2', 2, 'Cars - Passat - Vilas', 'trade_any_vehicle'),
(687, 'VIL_transit_civ', 2, 'Vans - Vilas', 'trade_any_vehicle'),
(688, 'VIL_transit_truck', 2, 'Vans Cargo - Vilas', 'trade_any_vehicle'),
(689, 'VIL_Star_S2000o', 2, 'Trucks Cargo - Vilas', 'trade_any_vehicle'),
(690, 'VIL_Star_S2000', 2, 'Trucks Cargo - Vilas', 'trade_any_vehicle'),
(691, 'VIL_sprinter_cargo', 2, 'Trucks Cargo - Vilas', 'trade_any_vehicle'),
(692, 'VIL_smart_civil3', 2, 'Cars - Smart - Vilas', 'trade_any_vehicle'),
(693, 'VIL_smart_civil4', 2, 'Cars - Smart - Vilas', 'trade_any_vehicle'),
(694, 'VIL_smart_civil2', 2, 'Cars - Smart - Vilas', 'trade_any_vehicle'),
(695, 'VIL_smart_civil', 2, 'Cars - Smart - Vilas', 'trade_any_vehicle');
INSERT IGNORE INTO `trader_items` VALUES(696, 'VIL_smart_civil1', 2, 'Cars - Smart - Vilas', 'trade_any_vehicle'),
(697, 'VIL_smart_civil5', 2, 'Cars - Smart - Vilas', 'trade_any_vehicle'),
(705, 'VIL_octavia_civil4', 2, 'Cars - Skoda - Vilas', 'trade_any_vehicle'),
(706, 'VIL_octavia_civil', 2, 'Cars - Skoda - Vilas', 'trade_any_vehicle'),
(707, 'VIL_octavia_civil2', 2, 'Cars - Skoda - Vilas', 'trade_any_vehicle'),
(708, 'VIL_octavia_civil3', 2, 'Cars - Skoda - Vilas', 'trade_any_vehicle'),
(709, 'VIL_fobia_civil', 2, 'Cars - Skoda Fabia - Vilas', 'trade_any_vehicle'),
(710, 'VIL_fobia_civil2', 2, 'Cars - Skoda Fabia - Vilas', 'trade_any_vehicle'),
(711, 'VIL_fobia_civil3', 2, 'Cars - Skoda Fabia - Vilas', 'trade_any_vehicle'),
(712, 'VIL_fobia_civil1', 2, 'Cars - Skoda Fabia - Vilas', 'trade_any_vehicle'),
(713, 'VIL_fobia_civil5', 2, 'Cars - Skoda Fabia - Vilas', 'trade_any_vehicle'),
(714, 'VIL_fobia_civil4', 2, 'Cars - Skoda Fabia - Vilas', 'trade_any_vehicle'),
(715, 'VIL_vivaro_civ', 2, 'Vans - Renault - Vilas', 'trade_any_vehicle'),
(716, 'VIL_asistvan', 2, 'Vans - Tow  - Vilas', 'trade_any_vehicle'),
(717, 'VIL_ducato_cargo2', 2, 'Vans - Cargo  - Vilas', 'trade_any_vehicle'),
(718, 'VIL_lublin_freez', 2, 'Truck - Cargo  - Vilas', 'trade_any_vehicle'),
(719, 'VIL_kia_ceeddwa3', 2, 'Cars - Kia CeeD 2  - Vilas', 'trade_any_vehicle'),
(720, 'VIL_kia_ceeddwa2', 2, 'Cars - Kia CeeD 2  - Vilas', 'trade_any_vehicle'),
(721, 'VIL_kia_ceeddwa4', 2, 'Cars - Kia CeeD 2  - Vilas', 'trade_any_vehicle'),
(722, 'VIL_kia_ceeddwa', 2, 'Cars - Kia CeeD 2  - Vilas', 'trade_any_vehicle'),
(723, 'VIL_kia_ceeddwa6', 2, 'Cars - Kia CeeD 2  - Vilas', 'trade_any_vehicle'),
(724, 'VIL_kia_ceeddwa5', 2, 'Cars - Kia CeeD 2  - Vilas', 'trade_any_vehicle'),
(725, 'VIL_kia_ceed3', 2, 'Cars - Kia CeeD  - Vilas', 'trade_any_vehicle'),
(726, 'VIL_kia_ceed', 2, 'Cars - Kia CeeD  - Vilas', 'trade_any_vehicle'),
(727, 'VIL_kia_ceed4', 2, 'Cars - Kia CeeD  - Vilas', 'trade_any_vehicle'),
(728, 'VIL_kia_ceed2', 2, 'Cars - Kia CeeD  - Vilas', 'trade_any_vehicle'),
(729, 'VIL_karoca_civil_red', 2, 'Cars - FSO Caro  - Vilas', 'trade_any_vehicle'),
(730, 'VIL_karoca_civil', 2, 'Cars - FSO Caro  - Vilas', 'trade_any_vehicle'),
(731, 'VIL_mondeo_civil2', 2, 'Cars - Ford Mondeo  - Vilas', 'trade_any_vehicle'),
(732, 'VIL_mondeo_civil', 2, 'Cars - Ford Mondeo  - Vilas', 'trade_any_vehicle'),
(733, 'VIL_mondeo_civil5', 2, 'Cars - Ford Mondeo  - Vilas', 'trade_any_vehicle'),
(734, 'VIL_mondeo_civil4', 2, 'Cars - Ford Mondeo  - Vilas', 'trade_any_vehicle'),
(735, 'VIL_mondeo_civil1', 2, 'Cars - Ford Mondeo  - Vilas', 'trade_any_vehicle'),
(736, 'VIL_mondeo_civil3', 2, 'Cars - Ford Mondeo  - Vilas', 'trade_any_vehicle'),
(737, 'VIL_panda_civil', 2, 'Cars - Fiat Panda - Vilas', 'trade_any_vehicle'),
(738, 'VIL_panda_civil1', 2, 'Cars - Fiat Panda  - Vilas', 'trade_any_vehicle'),
(739, 'VIL_ducato_cargo', 2, 'Vans - Cargo - Vilas', 'trade_any_vehicle'),
(740, 'VIL_ducato_bus', 2, 'Vans - Vilas', 'trade_any_vehicle'),
(741, 'VIL_citrone_civil1', 2, 'Cars - Citroen - Vilas', 'trade_any_vehicle'),
(742, 'VIL_citrone_civil3', 2, 'Cars - Citroen - Vilas', 'trade_any_vehicle'),
(743, 'VIL_citrone_civil', 2, 'Cars - Citroen - Vilas', 'trade_any_vehicle'),
(744, 'VIL_citrone_civil2', 2, 'Cars - Citroen - Vilas', 'trade_any_vehicle'),
(745, 'VIL_berlingo', 2, 'Vans - Citroen - Vilas', 'trade_any_vehicle'),
(746, 'VIL_bmw7_civilvip', 2, 'Cars - BMW - Vilas', 'trade_any_vehicle'),
(747, 'VIL_bmw7_civil1', 2, 'Cars - BMW - Vilas', 'trade_any_vehicle'),
(748, 'VIL_bmw7_civil', 2, 'Cars - BMW - Vilas', 'trade_any_vehicle'),
(749, 'VIL_bmw7_civil2', 2, 'Cars - BMW - Vilas', 'trade_any_vehicle'),
(750, 'VIL_vivaro_amb', 2, 'Vans - AMB - Vilas', 'trade_any_vehicle'),
(751, 'VIL_alfa_civil2', 2, 'Cars - Alfa Romeo - Vilas', 'trade_any_vehicle'),
(752, 'VIL_alfa_civil', 2, 'Cars - Alfa Romeo - Vilas', 'trade_any_vehicle'),
(753, 'VIL_alfa_civil1', 2, 'Cars - Alfa Romeo - Vilas', 'trade_any_vehicle'),
(754, 'VIL_hilux1_police', 2, 'Trucks - Police - Vilas', 'trade_any_vehicle'),
(755, 'GNT_C185U', 2, 'Plane', 'trade_any_vehicle'),
(756, 'GNT_C185', 2, 'Plane', 'trade_any_vehicle'),
(757, 'GNT_C185R', 2, 'Plane', 'trade_any_vehicle'),
(758, 'GNT_C185C', 2, 'Plane', 'trade_any_vehicle'),
(759, 'ItemSodaOrangeSherbet', 1, 'Drink', 'trade_items'),
(761, 'ItemSodaR4z0r', 1, 'Drink', 'trade_items'),
(762, 'FoodMRE', 1, 'Food', 'trade_items'),
(763, 'FoodPistachio', 1, 'Food', 'trade_items'),
(764, 'FoodNutmix', 1, 'Food', 'trade_items'),
(765, 'ItemFuelBarrel', 1, 'Car Parts', 'trade_items'),
(766, 'ItemFuelBarrelEmpty', 1, 'Car Parts', 'trade_items'),
(767, 'bulk_PartGeneric', 1, 'Wholesale Crates', 'trade_items'),
(768, 'bulk_ItemWire', 1, 'Wholesale Crates', 'trade_items'),
(769, 'bulk_ItemTankTrap', 1, 'Wholesale Crates', 'trade_items');
SET FOREIGN_KEY_CHECKS=1;